CREATE TABLE IF NOT EXISTS users (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name varchar,
email varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS request (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
description varchar NOT NULL,
requestor_id BIGINT,
CONSTRAINT users FOREIGN KEY(requestor_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS items (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name varchar NOT NULL,
description varchar NOT NULL,
available boolean,
owner_id BIGINT,
request_id BIGINT,
CONSTRAINT users FOREIGN KEY (owner_id) REFERENCES users (id),
CONSTRAINT itemRequest FOREIGN KEY (request_id) REFERENCES request (id)
);

CREATE TABLE IF NOT EXISTS bookings (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
start_time TIMESTAMP WITHOUT TIME ZONE,
end_time TIMESTAMP WITHOUT TIME ZONE,
item_id BIGINT,
booker_id BIGINT,
status varchar,
CONSTRAINT items FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
CONSTRAINT users FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
text varchar,
item_id BIGINT,
author_id BIGINT,
created TIMESTAMP WITHOUT TIME ZONE,
CONSTRAINT items FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
CONSTRAINT users FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);

